[phases.install]
# هنثبت المكتبات من المكان اللي فيه الـ package.json
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
# هندخل جوه فولدر السيرفر ونعمل Build
cmds = ["cd server && pnpm build"]

[start]
# هنقوم السيرفر من المسار اللي نتج عن الـ build
cmd = "node server/dist/index.js"