[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
# هننفذ أمر الـ build اللي أنت وريهولي في الـ package.json
# ده هيعمل Vite build للفرونت إند و esbuild للباك إند
cmds = ["pnpm run build"]

[start]
# هننفذ أمر الـ start اللي متعرف عندك بالظبط
cmd = "pnpm run start"